repos:
  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22  # Use the ref you want to point at
    hooks:
      - id: mdformat
        # Optionally add plugins
        additional_dependencies: [mdformat-gfm]
        args: ["--wrap", "80", "--number"]
